# gim compression profile: zstd
# ZStandard — best ratio+speed balance. Recommended for most games.

name = "zstd"
description = "ZStandard — best balance of ratio and speed"

[precomp]
codecs = "auto"
chunk_size = "64mb"
depth = 0
dbase = true
dedup = true
low_memory = false
skip_verify = false
threads = "0"

[compress]
algorithm = "zstd"
level = 19
threads = "0"
